const CONTRACT_STATUS = {
  PENDING: "PENDING",
  SIGNED: "SIGNED",
  ACTIVE: "ACTIVE",
  COMPLETED: "COMPLETED"
};

const SERVICE_CATEGORIES = [
  "CATERING",
  "AV",
  "DECOR",
  "SECURITY",
  "PHOTOGRAPHY"
];

module.exports = { CONTRACT_STATUS, SERVICE_CATEGORIES };
