#!/bin/sh
set -eu

export VAULT_ADDR="${VAULT_ADDR:-http://vault:8200}"
export VAULT_TOKEN="${VAULT_TOKEN:?VAULT_TOKEN is required}"

until vault status >/dev/null 2>&1; do
  sleep 2
done

if ! vault secrets list -format=json | grep -q '"secret/"'; then
  vault secrets enable -path=secret kv-v2 >/dev/null
fi

if ! vault auth list -format=json | grep -q '"approle/"'; then
  vault auth enable approle >/dev/null
fi

vault policy write eventzen-local - <<'EOF'
path "secret/data/eventzen/local" {
  capabilities = ["read"]
}
EOF

vault write auth/approle/role/eventzen-local \
  token_policies="eventzen-local" \
  token_ttl="1h" \
  token_max_ttl="4h" \
  secret_id_ttl="30m" >/dev/null

vault kv put secret/eventzen/local \
  FRONTEND_ORIGIN="${FRONTEND_ORIGIN}" \
  AUTH_APP_BASE_URL="${AUTH_APP_BASE_URL}" \
  AUTH_DB_URL="${AUTH_DB_URL}" \
  AUTH_DB_USERNAME="${AUTH_DB_USERNAME}" \
  AUTH_DB_PASSWORD="${AUTH_DB_PASSWORD}" \
  EVENT_DB_URL="${EVENT_DB_URL}" \
  EVENT_DB_USERNAME="${EVENT_DB_USERNAME}" \
  EVENT_DB_PASSWORD="${EVENT_DB_PASSWORD}" \
  FINANCE_DB_URL="${FINANCE_DB_URL}" \
  FINANCE_DB_USERNAME="${FINANCE_DB_USERNAME}" \
  FINANCE_DB_PASSWORD="${FINANCE_DB_PASSWORD}" \
  AUTH_JWT_SECRET="${AUTH_JWT_SECRET}" \
  AUTH_JWT_ISSUER="${AUTH_JWT_ISSUER}" \
  AUTH_CRYPTO_SECRET="${AUTH_CRYPTO_SECRET}" \
  AUTH_BOOTSTRAP_ADMIN_EMAIL="${AUTH_BOOTSTRAP_ADMIN_EMAIL}" \
  AUTH_BOOTSTRAP_ADMIN_PASSWORD="${AUTH_BOOTSTRAP_ADMIN_PASSWORD}" \
  AUTH_BOOTSTRAP_ADMIN_FIRST_NAME="${AUTH_BOOTSTRAP_ADMIN_FIRST_NAME}" \
  AUTH_BOOTSTRAP_ADMIN_LAST_NAME="${AUTH_BOOTSTRAP_ADMIN_LAST_NAME}" \
  AUTH_PASSWORD_RESET_MINUTES="${AUTH_PASSWORD_RESET_MINUTES}" \
  AUTH_EMAIL_VERIFICATION_HOURS="${AUTH_EMAIL_VERIFICATION_HOURS}" \
  AUTH_REQUIRE_VERIFIED_EMAIL_FOR_LOGIN="${AUTH_REQUIRE_VERIFIED_EMAIL_FOR_LOGIN}" \
  AUTH_EXPOSE_DEBUG_TOKENS="${AUTH_EXPOSE_DEBUG_TOKENS}" \
  AUTH_ALLOW_DEBUG_GOOGLE_TOKENS="${AUTH_ALLOW_DEBUG_GOOGLE_TOKENS}" \
  AUTH_GOOGLE_CLIENT_ID="${AUTH_GOOGLE_CLIENT_ID}" \
  AUTH_SMTP_HOST="${AUTH_SMTP_HOST}" \
  AUTH_SMTP_PORT="${AUTH_SMTP_PORT}" \
  AUTH_SMTP_USERNAME="${AUTH_SMTP_USERNAME}" \
  AUTH_SMTP_PASSWORD="${AUTH_SMTP_PASSWORD}" \
  AUTH_SMTP_AUTH="${AUTH_SMTP_AUTH}" \
  AUTH_SMTP_STARTTLS="${AUTH_SMTP_STARTTLS}" \
  AUTH_SMTP_CONNECTION_TIMEOUT="${AUTH_SMTP_CONNECTION_TIMEOUT}" \
  AUTH_SMTP_TIMEOUT="${AUTH_SMTP_TIMEOUT}" \
  AUTH_SMTP_WRITE_TIMEOUT="${AUTH_SMTP_WRITE_TIMEOUT}" \
  AUTH_MAIL_FROM_EMAIL="${AUTH_MAIL_FROM_EMAIL}" \
  AUTH_MAIL_FROM_NAME="${AUTH_MAIL_FROM_NAME}" \
  NOTIFICATION_INTERNAL_SERVICE_KEY="${NOTIFICATION_INTERNAL_SERVICE_KEY}" \
  TICKETING_INTERNAL_SERVICE_KEY="${TICKETING_INTERNAL_SERVICE_KEY}" \
  VENUE_VENDOR_INTERNAL_SERVICE_KEY="${VENUE_VENDOR_INTERNAL_SERVICE_KEY}" \
  VENUE_VENDOR_MONGO_URI="${VENUE_VENDOR_MONGO_URI}" \
  NOTIFICATION_MONGO_URI="${NOTIFICATION_MONGO_URI}" \
  TICKETING_MONGO_CONNECTION_STRING="${TICKETING_MONGO_CONNECTION_STRING}" \
  TICKETING_MONGO_DATABASE="${TICKETING_MONGO_DATABASE}" \
  EVENT_STORAGE_ENABLED="${EVENT_STORAGE_ENABLED}" \
  EVENT_STORAGE_ENDPOINT="${EVENT_STORAGE_ENDPOINT}" \
  EVENT_STORAGE_ACCESS_KEY="${EVENT_STORAGE_ACCESS_KEY}" \
  EVENT_STORAGE_SECRET_KEY="${EVENT_STORAGE_SECRET_KEY}" \
  EVENT_STORAGE_BUCKET="${EVENT_STORAGE_BUCKET}" \
  EVENT_STORAGE_PUBLIC_BASE_URL="${EVENT_STORAGE_PUBLIC_BASE_URL}" \
  EVENT_STORAGE_EVENT_BANNERS_PREFIX="${EVENT_STORAGE_EVENT_BANNERS_PREFIX}" \
  EVENT_STORAGE_SPEAKER_PHOTOS_PREFIX="${EVENT_STORAGE_SPEAKER_PHOTOS_PREFIX}" \
  MINIO_TICKET_PASSES_PREFIX="${MINIO_TICKET_PASSES_PREFIX}" \
  MINIO_INVOICES_PREFIX="${MINIO_INVOICES_PREFIX}" \
  FINANCE_RAZORPAY_ENABLED="${FINANCE_RAZORPAY_ENABLED}" \
  FINANCE_RAZORPAY_KEY_ID="${FINANCE_RAZORPAY_KEY_ID}" \
  FINANCE_RAZORPAY_KEY_SECRET="${FINANCE_RAZORPAY_KEY_SECRET}" \
  FINANCE_RAZORPAY_CHECKOUT_NAME="${FINANCE_RAZORPAY_CHECKOUT_NAME}" \
  FINANCE_RAZORPAY_CHECKOUT_DESCRIPTION="${FINANCE_RAZORPAY_CHECKOUT_DESCRIPTION}" \
  NOTIFICATION_SMTP_HOST="${NOTIFICATION_SMTP_HOST}" \
  NOTIFICATION_SMTP_PORT="${NOTIFICATION_SMTP_PORT}" \
  NOTIFICATION_SMTP_USERNAME="${NOTIFICATION_SMTP_USERNAME}" \
  NOTIFICATION_SMTP_PASSWORD="${NOTIFICATION_SMTP_PASSWORD}" \
  NOTIFICATION_SMTP_AUTH="${NOTIFICATION_SMTP_AUTH}" \
  NOTIFICATION_SMTP_STARTTLS="${NOTIFICATION_SMTP_STARTTLS}" \
  NOTIFICATION_MAIL_FROM_EMAIL="${NOTIFICATION_MAIL_FROM_EMAIL}" \
  NOTIFICATION_MAIL_FROM_NAME="${NOTIFICATION_MAIL_FROM_NAME}" \
  NOTIFICATION_FIREBASE_PROJECT_ID="${NOTIFICATION_FIREBASE_PROJECT_ID}" \
  NOTIFICATION_FIREBASE_CLIENT_EMAIL="${NOTIFICATION_FIREBASE_CLIENT_EMAIL}" \
  NOTIFICATION_FIREBASE_PRIVATE_KEY="${NOTIFICATION_FIREBASE_PRIVATE_KEY}" \
  NOTIFICATION_SERVICE_BASE_URL="${NOTIFICATION_SERVICE_BASE_URL}" \
  EVENT_SERVICE_BASE_URL="${EVENT_SERVICE_BASE_URL}" \
  VENUE_VENDOR_SERVICE_BASE_URL="${VENUE_VENDOR_SERVICE_BASE_URL}" \
  VENUE_VENDOR_SERVICE_URL="${VENUE_VENDOR_SERVICE_URL}" \
  TICKETING_SERVICE_BASE_URL="${TICKETING_SERVICE_BASE_URL}" \
  TICKETING_SERVICE_URL="${TICKETING_SERVICE_URL}" \
  NOTIFICATION_SERVICE_URL="${NOTIFICATION_SERVICE_URL}" \
  KAFKA_BROKERS="${KAFKA_BROKERS}" \
  REDIS_URL="${REDIS_URL}" \
  ENABLE_KAFKA="${ENABLE_KAFKA}" \
  ENABLE_BULLMQ="${ENABLE_BULLMQ}" \
  ENABLE_SOCKET_IO="${ENABLE_SOCKET_IO}" \
  SEED_DEFAULT_TEMPLATES="${SEED_DEFAULT_TEMPLATES}" \
  DEFAULT_NOTIFICATION_LOCALE="${DEFAULT_NOTIFICATION_LOCALE}" \
  NOTIFICATION_RETENTION_DAYS="${NOTIFICATION_RETENTION_DAYS}" \
  OTEL_EXPORTER_OTLP_ENDPOINT="${OTEL_EXPORTER_OTLP_ENDPOINT}" \
  MANAGEMENT_TRACING_SAMPLING_PROBABILITY="${MANAGEMENT_TRACING_SAMPLING_PROBABILITY}" >/dev/null

vault read -field=role_id auth/approle/role/eventzen-local/role-id > /vault/approle/role-id
vault write -wrap-ttl=30m -field=wrapping_token -f auth/approle/role/eventzen-local/secret-id > /vault/approle/secret-id

chmod 0400 /vault/approle/role-id /vault/approle/secret-id
echo "Vault local bootstrap completed."
